language: rust
services:
  - docker
rust:
  - stable
  - beta
  - nightly
addons:
  apt:
    packages:
      - binutils-dev
      - build-essential
      - expect
      - pkg-config
      - zlib1g-dev
      - libssh2-1-dev
      - libssl-dev
cache:
  apt: true
  directories:
    - tests/tmp
    - target/debug/deps
    - target/debug/build
    - target/release/deps
notifications:
  email:
    on_success: never
    on_failure: never
branches:
  only:
    - main
    - ci
env:
  - REDIS_VERSION=6.2.2
before_script:
  - ./tests/scripts/install_redis_centralized.sh
  - ./tests/scripts/install_redis_clustered.sh
  - ./tests/scripts/docker-install-redis-sentinel.sh
jobs:
  allow_failures:
    - rust: nightly
  fast_finish: true
script:
  - ./tests/run_all.sh
