#!/bin/bash

export RUST_BACKTRACE=full \
  REDIS_VERSION=6.2.2 \
  REDIS_USERNAME=foo \
  REDIS_PASSWORD=bar \
  REDIS_SENTINEL_PASSWORD=baz \
  FRED_REDIS_CLUSTER_HOST=127.0.0.1 \
  FRED_REDIS_CLUSTER_PORT=30001 \
  FRED_REDIS_CENTRALIZED_HOST=127.0.0.1 \
  FRED_REDIS_CENTRALIZED_PORT=6379

alias fred_redis_cli='./tests/tmp/redis_$REDIS_VERSION/redis-$REDIS_VERSION/src/redis-cli "$@"'

if [ -z "$CIRCLECI_TESTS" ]; then
  read -p "Use cargo nextest? [y/n]: " NEXTEST
  if [ "$NEXTEST" = "y" ]; then
    export FRED_CI_NEXTEST=1
  else
    unset FRED_CI_NEXTEST
  fi
fi