version: '2'

services:
  sentinel-tests:
    depends_on:
      - redis-main
      - redis-replica
      - redis-sentinel-3
    container_name: "sentinel-tests"
    build:
      context: ..
      dockerfile: .circleci/Dockerfile.sentinel
      args:
        REDIS_VERSION: "${REDIS_VERSION}"
        REDIS_USERNAME: "${REDIS_USERNAME}"
        REDIS_PASSWORD: "${REDIS_PASSWORD}"
        REDIS_SENTINEL_PASSWORD: "${REDIS_SENTINEL_PASSWORD}"
        FRED_CI_NEXTEST: "${FRED_CI_NEXTEST}"
    networks:
      - app-tier
    environment:
      CIRCLECI_TESTS: "1"
      REDIS_VERSION: "${REDIS_VERSION}"
      REDIS_USERNAME: "${REDIS_USERNAME}"
      REDIS_PASSWORD: "${REDIS_PASSWORD}"
      REDIS_SENTINEL_PASSWORD: "${REDIS_SENTINEL_PASSWORD}"
      FRED_CI_NEXTEST: "${FRED_CI_NEXTEST}"