[package]
name = "pipeline_test"
version = "0.1.0"
authors = ["Alec Embke <aembke@gmail.com>"]
edition = "2018"
description = "A script to test pipelining commands with tracing."

[profile.release]
debug = true

[dependencies]
clap = { version = "2.33", features = ["yaml"] }
opentelemetry = { version = "0.18.0", features = ["rt-tokio", "trace"] }
opentelemetry-jaeger = { version = "0.17.0", features = ["tokio", "isahc_collector_client", "isahc", "collector_client", "rt-tokio"] }
tracing-attributes = "0.1.23"
tracing-opentelemetry = "0.18.0"
tracing-core = "0.1.30"
tracing-subscriber = "0.3.16"
tracing = "0.1.37"
log = "0.4"
pretty_env_logger = "0.4"
tokio = { version = "1", features = ["full"] }
futures = "0.3"
rand = "0.8"
indicatif = "=0.17.1"

[dependencies.fred]
path = "../.."
features = ["ignore-auth-error"]
default-features = false

[features]
default = []
debug-ids = ["fred/debug-ids"]
stdout-tracing = ["fred/partial-tracing"]
partial-tracing = ["fred/partial-tracing"]
full-tracing = ["fred/full-tracing"]
blocking-encoding = ["fred/blocking-encoding"]