version: '2'

services:
  pipeline-test:
    depends_on:
      - redis-main
      - redis-cluster-6
    container_name: "pipeline-test"
    build:
      context: ../../../
      dockerfile: tests/docker/runners/images/base.dockerfile
      args:
        REDIS_VERSION: "${REDIS_VERSION}"
    networks:
      - app-tier
    environment:
      RUST_LOG: "${RUST_LOG}"
      REDIS_VERSION: "${REDIS_VERSION}"
    volumes:
      - "../../../bin/pipeline_test:/project"
      - "../../..:/fred"
      - "~/.cargo/registry:/usr/local/cargo/registry"