version: '2'

services:
  fred-benchmark:
    depends_on:
      - redis-main
      - redis-cluster-6
    container_name: "fred-benchmark"
    build:
      context: ../../../
      dockerfile: tests/docker/runners/images/base.dockerfile
      args:
        REDIS_VERSION: "${REDIS_VERSION}"
    networks:
      - fred-tests
    environment:
      RUST_LOG: "${RUST_LOG}"
      REDIS_VERSION: "${REDIS_VERSION}"
    volumes:
      - "../../../bin/benchmark:/project"
      - "../../..:/fred"
      - "~/.cargo/registry:/usr/local/cargo/registry"