#!/bin/bash
. $ROOT/tests/chaos_monkey/util.sh
check_env
check_move_env

SRC_ID=`$REDIS_CLI_PATH -p $SRC_SERVER_PORT --raw CLUSTER MYID`
DEST_ID=`$REDIS_CLI_PATH -p $DEST_SERVER_PORT --raw CLUSTER MYID`
echo "Moving 'foo' from $SRC_ID ($SRC_SERVER_PORT) to $DEST_ID ($DEST_SERVER_PORT)"

#$REDIS_CLI_PATH -p $DEST_SERVER_PORT --raw CLUSTER SETSLOT 12182 IMPORTING $SRC_ID
#$REDIS_CLI_PATH -p $SRC_SERVER_PORT --raw CLUSTER SETSLOT 12182 MIGRATING $DEST_ID
#$REDIS_CLI_PATH -p $SRC_SERVER_PORT --raw MIGRATE 127.0.0.1 $DEST_SERVER_PORT "" 0 5000 KEYS foo
#$REDIS_CLI_PATH -p $DEST_SERVER_PORT --raw CLUSTER SETSLOT 12182 NODE $DEST_ID
