[package]
name = "pipeline_metrics"
version = "0.1.0"
edition = "2021"

[dependencies]
subprocess = "0.2"
indicatif = "=0.17.1"
log = "0.4"
pretty_env_logger = "0.4"
clap = { version = "2.33", features = ["yaml"] }
csv = "1.1"