version: '2'

services:
  pipeline-metrics:
    depends_on:
      - redis-main
      - redis-cluster-6
    container_name: "pipeline-metrics"
    build:
      context: ../../../
      dockerfile: tests/docker/runners/images/base.dockerfile
      args:
        REDIS_VERSION: "${REDIS_VERSION}"
    networks:
      - app-tier
    environment:
      RUST_LOG: "${RUST_LOG}"
      REDIS_VERSION: "${REDIS_VERSION}"
    volumes:
      - "../../../bin/pipeline_metrics:/project"
      - "../../..:/fred"
      - "~/.cargo/bin/sccache:/usr/local/cargo/bin/sccache"
      - "~/.cargo/registry:/usr/local/cargo/registry"
      - "~/.cache/sccache:/home/root/.cache/sccache"